use crate::analysis::CrateInfo;

/// Generate a full README.md from crate info.
pub fn generate_readme(info: &CrateInfo) -> anyhow::Result<String> {
    let mut md = String::new();

    // Title
    md.push_str(&format!("# {}\n\n", info.name));

    // Description
    if let Some(desc) = &info.description {
        md.push_str(&format!("{}\n\n", desc));
    } else {
        md.push_str(&format!(
            "A Rust crate for {}.\n\n",
            humanize_name(&info.name)
        ));
    }

    // Badges
    md.push_str(&generate_badges(info));
    md.push('\n');

    // Table of Contents
    if has_enough_sections(info) {
        md.push_str("## Table of Contents\n\n");
        md.push_str("- [Features](#features)\n");
        md.push_str("- [Installation](#installation)\n");
        md.push_str("- [Usage](#usage)\n");
        if !info.public_api.is_empty() {
            md.push_str("- [API Reference](#api-reference)\n");
        }
        if !info.test_functions.is_empty() {
            md.push_str("- [Testing](#testing)\n");
        }
        md.push_str("- [Dependencies](#dependencies)\n");
        if info.license.is_some() {
            md.push_str("- [License](#license)\n");
        }
        md.push('\n');
    }

    // Features
    md.push_str("## Features\n\n");
    let features = generate_features(info);
    md.push_str(&features);
    md.push('\n');

    // Installation
    md.push_str("## Installation\n\n");
    md.push_str(&generate_installation(info));
    md.push('\n');

    // Usage
    md.push_str("## Usage\n\n");
    md.push_str(&generate_usage(info));
    md.push('\n');

    // API Reference
    if !info.public_api.is_empty() {
        md.push_str("## API Reference\n\n");
        md.push_str(&generate_api_reference(info));
        md.push('\n');
    }

    // Testing
    if !info.test_functions.is_empty() {
        md.push_str("## Testing\n\n");
        md.push_str(&format!(
            "This crate includes **{}** test{}:\n\n",
            info.test_functions.len(),
            if info.test_functions.len() == 1 { "" } else { "s" }
        ));
        for test in &info.test_functions {
            let desc = test_name_to_description(&test.name);
            md.push_str(&format!("- **`{}`** — {}\n", test.name, desc));
        }
        md.push('\n');
        md.push_str("Run the test suite:\n\n");
        md.push_str("```bash\n");
        md.push_str("cargo test\n");
        md.push_str("```\n\n");
    }

    // Dependencies
    if !info.dependencies.is_empty() {
        md.push_str("## Dependencies\n\n");
        md.push_str(&format!(
            "{} runtime {}:\n\n",
            info.dependencies.len(),
            if info.dependencies.len() == 1 { "dependency" } else { "dependencies" }
        ));
        for dep in &info.dependencies {
            md.push_str(&format!("- `{}`\n", dep));
        }
        md.push('\n');
    }

    // License
    if let Some(lic) = &info.license {
        md.push_str("## License\n\n");
        md.push_str(&format!("Licensed under {}.\n", lic));
    } else {
        md.push_str("## License\n\n");
        md.push_str("See [LICENSE](./LICENSE) for details.\n");
    }

    // Footer
    md.push_str(&format!(
        "\n---\n\n*Generated by [readme-generator](https://github.com/SuperInstance/readme-generator)*\n"
    ));

    Ok(md)
}

fn generate_badges(info: &CrateInfo) -> String {
    let mut badges = String::new();

    // Version badge
    badges.push_str(&format!(
        "![Version](https://img.shields.io/badge/version-{}-blue)\n",
        info.version
    ));

    // License badge
    if let Some(lic) = &info.license {
        badges.push_str(&format!(
            "![License](https://img.shields.io/badge/license-{}-green)\n",
            lic.replace('-', "--")
        ));
    }

    // Edition badge
    if let Some(ed) = &info.edition {
        badges.push_str(&format!(
            "![Rust](https://img.shields.io/badge/rust-{}-orange)\n",
            ed
        ));
    }

    // Test count badge
    if !info.test_functions.is_empty() {
        badges.push_str(&format!(
            "![Tests](https://img.shields.io/badge/tests-{}-brightgreen)\n",
            info.test_functions.len()
        ));
    }

    badges
}

fn generate_features(info: &CrateInfo) -> String {
    let mut features = String::new();

    if info.public_api.is_empty() && info.test_functions.is_empty() {
        features.push_str("A Rust project. See usage below for details.\n");
        return features;
    }

    // Generate features from public API items
    for s in &info.public_api.structs {
        let desc = if let Some(doc) = s.doc_comments.first() {
            doc.clone()
        } else {
            format!("{} type", humanize_name(&s.name))
        };
        features.push_str(&format!("- **{}** — {}\n", s.name, desc));
    }

    for e in &info.public_api.enums {
        let desc = if let Some(doc) = e.doc_comments.first() {
            doc.clone()
        } else {
            format!("{} enumeration", humanize_name(&e.name))
        };
        features.push_str(&format!("- **{}** — {}\n", e.name, desc));
    }

    for t in &info.public_api.traits {
        let desc = if let Some(doc) = t.doc_comments.first() {
            doc.clone()
        } else {
            format!("{} trait", humanize_name(&t.name))
        };
        features.push_str(&format!("- **{}** — {}\n", t.name, desc));
    }

    // Summarize functions
    if !info.public_api.functions.is_empty() {
        if info.public_api.functions.len() <= 10 {
            for f in &info.public_api.functions {
                let desc = if let Some(doc) = f.doc_comments.first() {
                    doc.clone()
                } else {
                    format!("`{}` function", f.name)
                };
                features.push_str(&format!("- **{}()** — {}\n", f.name, desc));
            }
        } else {
            features.push_str(&format!(
                "- **{} public functions** — see API reference below\n",
                info.public_api.functions.len()
            ));
        }
    }

    features
}

fn generate_installation(info: &CrateInfo) -> String {
    let mut s = String::new();

    if !info.binary_targets.is_empty() {
        s.push_str("Install with Cargo:\n\n");
        s.push_str("```bash\n");
        s.push_str(&format!("cargo install {}\n", info.name));
        s.push_str("```\n\n");
    }

    s.push_str("Add to your `Cargo.toml`:\n\n");
    s.push_str("```toml\n");
    s.push_str(&format!("[dependencies]\n"));
    s.push_str(&format!(
        "{} = \"{}\"\n",
        info.name, info.version
    ));
    s.push_str("```\n\n");

    s.push_str("Or use as a Git dependency:\n\n");
    s.push_str("```toml\n");
    s.push_str("[dependencies]\n");
    if let Some(repo) = &info.repository {
        s.push_str(&format!(
            "{} = {{ git = \"{}\" }}\n",
            info.name, repo
        ));
    } else {
        s.push_str(&format!(
            "{} = {{ git = \"https://github.com/SuperInstance/{}\" }}\n",
            info.name, info.name
        ));
    }
    s.push_str("```\n");

    s
}

fn generate_usage(info: &CrateInfo) -> String {
    let mut s = String::new();

    // Generate usage examples from test functions
    if !info.test_functions.is_empty() {
        s.push_str("### Examples\n\n");
        s.push_str(&format!(
            "Based on the test suite ({} tests), here are usage patterns:\n\n",
            info.test_functions.len()
        ));

        for test in info.test_functions.iter().take(5) {
            let desc = test_name_to_description(&test.name);
            s.push_str(&format!("**{}**\n", desc));
            s.push_str("```rust\n");
            s.push_str(&generate_example_from_test(test, info));
            s.push_str("```\n\n");
        }

        if info.test_functions.len() > 5 {
            s.push_str(&format!(
                "... and {} more tests. See the source for full examples.\n\n",
                info.test_functions.len() - 5
            ));
        }
    } else if !info.public_api.functions.is_empty() {
        s.push_str("```rust\n");
        s.push_str(&format!("use {}::*;\n\n", info.name.replace('-', "_")));
        if let Some(f) = info.public_api.functions.first() {
            s.push_str(&format!(
                "// Example: {}()\n",
                f.name
            ));
            s.push_str(&format!(
                "let result = {}(/* ... */);\n",
                f.name
            ));
        }
        s.push_str("```\n\n");
    } else if !info.public_api.structs.is_empty() {
        s.push_str("```rust\n");
        s.push_str(&format!("use {}::*;\n\n", info.name.replace('-', "_")));
        if let Some(st) = info.public_api.structs.first() {
            s.push_str(&format!("let {} = {}::new(/* ... */);\n", 
                st.name.to_lowercase(),
                st.name
            ));
        }
        s.push_str("```\n\n");
    } else {
        s.push_str("```rust\n");
        s.push_str(&format!("// See crate documentation for usage\n"));
        s.push_str("```\n\n");
    }

    s
}

fn generate_api_reference(info: &CrateInfo) -> String {
    let mut s = String::new();
    let crate_ident = info.name.replace('-', "_");

    if !info.public_api.structs.is_empty() {
        s.push_str("### Structs\n\n");
        for st in &info.public_api.structs {
            s.push_str(&format!("#### `{}`\n\n", st.name));
            if !st.doc_comments.is_empty() {
                for doc in &st.doc_comments {
                    s.push_str(&format!("{}\n\n", doc));
                }
            }
        }
    }

    if !info.public_api.enums.is_empty() {
        s.push_str("### Enums\n\n");
        for en in &info.public_api.enums {
            s.push_str(&format!("#### `{}`\n\n", en.name));
            if !en.doc_comments.is_empty() {
                for doc in &en.doc_comments {
                    s.push_str(&format!("{}\n\n", doc));
                }
            }
        }
    }

    if !info.public_api.traits.is_empty() {
        s.push_str("### Traits\n\n");
        for tr in &info.public_api.traits {
            s.push_str(&format!("#### `{}`\n\n", tr.name));
            if !tr.doc_comments.is_empty() {
                for doc in &tr.doc_comments {
                    s.push_str(&format!("{}\n\n", doc));
                }
            }
        }
    }

    if !info.public_api.functions.is_empty() {
        s.push_str("### Functions\n\n");
        s.push_str("| Function | Description |\n");
        s.push_str("|----------|-------------|\n");
        for f in &info.public_api.functions {
            let desc = f
                .doc_comments
                .first()
                .cloned()
                .unwrap_or_else(|| "_No documentation_".to_string());
            s.push_str(&format!("| `{}()` | {} |\n", f.name, desc));
        }
        s.push('\n');
    }

    s
}

fn generate_example_from_test(test: &crate::analysis::TestFn, info: &CrateInfo) -> String {
    let crate_ident = info.name.replace('-', "_");
    let name_desc = test_name_to_description(&test.name);

    let mut s = String::new();
    s.push_str(&format!("// {}\n", name_desc));
    s.push_str(&format!("use {}::*;\n\n", crate_ident));

    if let Some(body) = &test.body_summary {
        // Try to create a plausible example from the test body
        s.push_str(&format!("// {}\n", body.replace('"', "\\\"").replace('\n', " ")));
    } else {
        s.push_str("// Test logic");
    }

    s.push('\n');
    s
}

fn has_enough_sections(info: &CrateInfo) -> bool {
    !info.public_api.is_empty() || !info.test_functions.is_empty()
}

fn humanize_name(name: &str) -> String {
    name.replace('-', " ")
        .split_whitespace()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Convert a test function name like `test_user_can_login` to a description.
fn test_name_to_description(name: &str) -> String {
    let cleaned = name
        .trim_start_matches("test_")
        .trim_start_matches("test")
        .trim_start_matches('_')
        .replace('_', " ");
    let words: Vec<String> = cleaned
        .split_whitespace()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect();
    if words.is_empty() {
        name.to_string()
    } else {
        words.join(" ")
    }
}
